#!/usr/lib/expect -f

source [file dirname [info script]]/debug.tcl
dputs [info script]

proc box_open {host} {
	global HOSTS

	expect "login:"; send "$HOSTS($host,user)\r";
	expect "Password:"; send "$HOSTS($host,password)\r\r";
	expect "Welcome";
	expect -re "^(.*) #"
	set prompt $expect_out(0,string)
	dputs "wilson output: $prompt"
	set HOSTS($host,prompt) "testwilson"
	dputs "placeholder:$HOSTS($host,prompt)"

	box_sys_status
	!# x y
}

proc box_sys_status {} {
	log_user 0
	send "\r"; expect " #";
	send "get system status\r";
	expect "Password:"; send "\r\r";
	log_user 1
}
