#################################################
# config
set debugMode 1
set DEBUG 1

set curdir [file dirname [info script]]
puts [info script]

set srcdir .
set objdir $curdir
set outdir $curdir/log

#log_file
#log_file -a $curdir/log.console
#################################################


#################################################
# common library
source $curdir/lib/debug.tcl
source $curdir/lib/box.exp
#################################################


#################################################
# global variable
set HOSTS(pc,name) "my linux pc"
set HOSTS(pc,note) "my test box 111C"
set HOSTS(pc,ip) "192.168.1.121"

set HOSTS(box,name) "my linux pc"
set HOSTS(box,note) "my test box VM64"
set HOSTS(box,prompt) "" ;# Placeholder
set HOSTS(box,ip) "192.168.1.99"
set HOSTS(box,user) "admin"
set HOSTS(box,password) ""
#################################################

